spring.application.name=full-stack-jwt

spring.security.user.name = user
spring.security.user.password = thimira

spring.datasource.url=jdbc:postgresql://localhost:5432/jwt-security
spring.datasource.username=postgres
spring.datasource.password=thimira